services:
  - type: web
    name: escrow-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: dev
      - key: DB_URL
        value: jdbc:postgresql://dpg-d0u2rp63jp1c73faheag-a.oregon-postgres.render.com:5432/escrow_qjts
      - key: DB_USERNAME
        value: admin
      - key: DB_PASSWORD
        value: aAJ9uWyVp0tiA6icjG6HWfG8ATyAGXTe
      - key: RECAPTCHA_SITE
        value: 6Lf8SFArAAAAABrbWbSWhIdi39T96jcq_tgiweED
      - key: RECAPTCHA_SECRET
        value: 6Lf8SFArAAAAAEfeUChwopI-ZVneb8t4gdu7umJ_