services:
  - type: web
    name: escrow-backend
    runtime: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/backendEscro-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        value: ${DB_URL}
      - key: DB_USERNAME
        value: ${DB_USERNAME}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: RECAPTCHA_SITE
        value: ${RECAPTCHA_SITE}
      - key: RECAPTCHA_SECRET
        value: ${RECAPTCHA_SECRET}
