spring:
  datasource:
    url: jdbc:postgresql://dpg-d0u2rp63jp1c73faheag-a.oregon-postgres.render.com:5432/escrow_qjts
    username: admin
    password: aAJ9uWyVp0tiA6icjG6HWfG8ATyAGXTe
    driver-class-name: org.postgresql.Driver

# application-dev.yml
app:
  base-url: http://192.168.0.101:5173/access/